# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.1.20"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJSON = "1.7.3"
kotlinxCoroutines = "1.9.0"
kord = "0.15.0"
clikt = "5.0.1"
exposed = "0.61.0"
okhttp = "5.3.0"
mavenPublish = "0.35.0"
moeka = "0.0.1"
ktlint = "14.0.1"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration", version.ref = "exposed" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.2" }
slf4jApi = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.3.14" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version = "3.16.2" }
okhttp-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines", version.ref = "okhttp" }
moeka-core = { module = "dev.lizainslie.moeka:moeka-core", version.ref = "moeka" }
moeka-discord = { module = "dev.lizainslie.moeka:moeka-discord", version.ref = "moeka" }


[bundles]
kord = ["kord-core"]
exposed = ["exposed-core", "exposed-jdbc", "exposed-dao", "exposed-kotlin-datetime", "exposed-migration"]
logging = ["slf4jApi", "logback"]
okhttp = ["okhttp-core", "okhttp-coroutines"]
moeka = ["moeka-core", "moeka-discord"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-beta15" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }